DROP DATABASE IF EXISTS "ArticlesDB";
CREATE ROLE damola WITH LOGIN PASSWORD 'damola';
CREATE DATABASE "ArticlesDB";
\c ArticlesDB
CREATE TABLE IF NOT EXISTS ARTICLES(
ID SERIAL PRIMARY KEY,
TITLE VARCHAR(100) NOT NULL,
DESCRIPTION text NOT NULL,
THUMBNAIL_URL text NOT NULL,
SECTION VARCHAR(15) NOT NULL,
VIEWS INTEGER NOT NULL,
URL text NOT NULL
);
GRANT ALL PRIVILEGES ON ARTICLES TO damola;
GRANT ALL PRIVILEGES ON articles_id_seq to damola;
